require:
  - rubocop-rake

inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.7

Bundler/DuplicatedGem:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
   - "gemfiles/*.gemfile"
Style/SpecialGlobalVars:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
